// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdM8ox8t0uRL98ir2t5YKPi8Prtl0TTvg',
    appId: '1:642385853233:web:d0c0b1c507f92dadbc8e10',
    messagingSenderId: '642385853233',
    projectId: 'newquizapp-16502',
    authDomain: 'newquizapp-16502.firebaseapp.com',
    storageBucket: 'newquizapp-16502.appspot.com',
    measurementId: 'G-Y91SP700H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcBjgF3J1uOLJ66t4icYwajERBIx7ZME',
    appId: '1:642385853233:android:6a2b0d441a21ffb7bc8e10',
    messagingSenderId: '642385853233',
    projectId: 'newquizapp-16502',
    storageBucket: 'newquizapp-16502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-uIS3tBNQMjbQNaL-06kIm_AKnGbEcE',
    appId: '1:642385853233:ios:5e5994d9ddd2225fbc8e10',
    messagingSenderId: '642385853233',
    projectId: 'newquizapp-16502',
    storageBucket: 'newquizapp-16502.appspot.com',
    iosBundleId: 'com.hasanshukurov.quizApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-uIS3tBNQMjbQNaL-06kIm_AKnGbEcE',
    appId: '1:642385853233:ios:d4943e4f290f3687bc8e10',
    messagingSenderId: '642385853233',
    projectId: 'newquizapp-16502',
    storageBucket: 'newquizapp-16502.appspot.com',
    iosBundleId: 'com.hasanshukurov.quizApp1.RunnerTests',
  );
}
